## <center>2.feladatsor</center>

### <center>Norma, kondíciószámok</center>

<br>
<b>1.feladat.</b> Legyen $x=(10^{200}, 1)$. Számítsuk ki $x$ normáját az alábbi 2 két módon:

+ $||x||=\sqrt{x_1^2+x_2^2}$ és
+ $c=\max\left\{|x_1|+|x_2|\right\}$, $||x||=c\cdot\sqrt{\left(\frac{x_1}{c}\right)^2+\left(\frac{x_1}{c}\right)^2}$.




In [3]:
x=[10^200, 1];
x_norma_1=sqrt(x(1)^2+x(2)^2) % vagy (x(1)^2+x(2)^2)^(1/2)
c=max(abs(x(1)),abs(x(2))); 
x_norma_2=c*sqrt((x(1)/c)^2+(x(2)/c)^2)

x_norma_1 =  Inf
x_norma_2 =   1.0000e+200


<br>
<b>2.feladat.</b> A <i>max</i> és <i>abs</i> beépített függvények segítségével írjunk programot <i>p_max_norma.m</i> fájl néven, amely egy adott valós $x$ vektor felhasználó által kért $p$-normáját és maximumnormáját kiszámolja!

In [2]:
format long
x=[1 2 -3]
p=11
norma_p=(sum(abs(x).^p))^(1/p)
norma_max=max(abs(x))

% Fedezzuk fel a max, abs parancsokat!
% Mondjuk el a beepitett norm(x,p) es norm(x,'inf') parancsokat is!

x =

   1   2  -3

p =  11
norma_p =  3.003138080795621
norma_max =  3


In [4]:
[norma_p, norma_max]=p_max_norma([1 2 -3],11)

norma_p =  3.00313808079562
norma_max =  3


<br>
<b>3.feladat.</b> A <i>switch-case</i> szerkezet segítségével írjunk programot <i>indukaltmatrixnorma.m</i> fájl néven, mely adott négyzetes mátrixra és az egyes, kettes vagy vegtelen szavak input begépelése után kiszámolja $||A||_1$, $||A||_2$ vagy $||A||_{\infty}$ normáját! Ha nem négyzetes mátrixot vagy a fenti sztringek valamilyék adjuk meg, akkor a programunk adjon vissza hibaüzenetet!

In [2]:
% switch-szerkezet felfedezese, sztring, nemegyenlo, if-else szerkezet
% elotte norm matrixokra

A=[2 3; -1 5; 2 3]

if size(A,1) == size(A,1)
   disp('Negyzetes')
   else
   disp('Nem negyzetes')
end

A =

   2   3
  -1   5
   2   3

Negyzetes


In [5]:
indukaltmatrixnorma([1 2; 4 6; 2 2],'egyes')

Kerlek negyzetes matrixot gepelj be!


<br>
<b>4.feladat.</b> Tekintsük a második derivált közelítésére szolgáló centrális véges differenciahányadoshoz tartozó 
<br>

 $$A_n=\begin{pmatrix} 
    2 & -1 &  &  &  \\
    -1 & 2 & -1 &  & \\
     & \ddots & \ddots & \ddots & \\
     &   & -1 & 2 & -1 \\
     &  &  & -1 & 2
    \end{pmatrix}\in\mathbb{R}^{n \times n}$$
<br>
mátrixot, illetve az ún.
 $$H_n=\begin{pmatrix} 
     1 & 1/2 & 1/3 & \dots & 1/n \\
     1/2 & 1/3 & 1/4 & \dots & 1/(n+1)\\
     1/3 & 1/4 & 1/5 & \dots & 1/(n+2)\\
     \vdots & & & & \vdots \\
     1/n & 1/(n+1) & 1/(n+2) & \dots & 1/(2n-1)
      \end{pmatrix}\in\mathbb{R}^{n \times n}$$
<br>

Hilbert-mátrixot. Írjunk programot <i>speckondi.m</i> fájl néven, amely az alábbi két mátrix kettes kondíciószámát, valamint a <i>condest</i> értékét adja vissza adott $n$-re!

In [24]:
format long
N=5;
e=ones(N,1);
A=spdiags([-e 2*e -e], [-1 0 1], N, N); % spdiags felfedezese

for i=1:N
    for j=1:N
        H(i,j)=1/(i+j-1);
    end
end

cond(A,2)
cond(H,2)


condest(A) %nezzuk meg helpben, hogy mire valo
condest(H)
% hilb(5) % a beepiett parancs a Hilbert matrixra

ans =  13.92820323027551
ans =  476607.2502418646
ans =  17.99999999999999
ans =  943655.9999992513


In [6]:
[cond_A_2, cond_H_2, condest_A_2, condest_H_2]=speckondi(5)

cond_A_2 =  13.9282032302755
cond_H_2 =  476607.250243310
condest_A_2 =  18.0000000000000
condest_H_2 =  943655.999999934


<br>
<b>5.feladat.</b> Állítsuk elő azt az $A\in\mathbb{R}^{100 \times 100}$ mátrixot, melynek elemei az
<br>

$$
a_{ij}=
\begin{cases}
1, \text{ha}\ i=j\\
-1, \text{ha}\ i<j\\
0, \text{egyébként}
\end{cases}
$$
<br>

értékek. A lineáris algebrai egyenletrendszer jobboldali vektora $b=\left(-98,-97,\ldots,0,1\right)^T$. Pertulbáljuk a $b$ vektort úgy, hogy annak utolsó eleme $1$ helyett $1.0001$. Az előadáson tanultak fényében döntsük el, hogy a lineáris algebrai egyenletrendszer rosszul kondícionált-e vagy sem! Ehhez hasznájuk a 
<br>

$$
\text{cond}_p(A)\frac{||\delta b||_p}{||b||_p}\geq 1
$$
becslést!

In [4]:
N=32; A=diag(ones(N,1))+triu(-ones (N), 1);
b=[N-2:-1:0]; b=[-b 1]';
delta_b=[zeros(1,N-1) 0.0001]';
masodik_1=cond(A,1)*norm(delta_b,1)/norm(b,1)
masodik_2=cond(A,2)*norm(delta_b,2)/norm(b,2)
masodik_inf=cond(A,'inf')*norm(delta_b,'inf')/norm(b,'inf')


masodik_1 =  14746.66883
masodik_2 =  28668.09870
masodik_inf =  229064.92245


In [2]:
N=11
for i=1:N
    for j=1:i
        H(j,i)=1/(-1);
    end
end
H

N =  11
H =

  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   0   0  -1  -1  -1  -1  -1  -1  -1  -1  -1
   0   0   0  -1  -1  -1  -1  -1  -1  -1  -1
   0   0   0   0  -1  -1  -1  -1  -1  -1  -1
   0   0   0   0   0  -1  -1  -1  -1  -1  -1
   0   0   0   0   0   0  -1  -1  -1  -1  -1
   0   0   0   0   0   0   0  -1  -1  -1  -1
   0   0   0   0   0   0   0   0  -1  -1  -1
   0   0   0   0   0   0   0   0   0  -1  -1
   0   0   0   0   0   0   0   0   0   0  -1

