## <center>3. Feladatsor</center>

### <center>Lineár algebrai egyenletrendszer megoldhatósági tételköre</center>

<b>1.feladat.</b> Írjunk programot <i>nullasajatertek.m</i> néven, amely eldönti egy adott négyzetes mátrixról, hogy a nulla sajátértéke-e vagy sem, azaz hogy az $A$ mátrix invertálható-e vagy sem!

In [1]:
% Nulla s.é. vagy sem
%A=[1 2 6; 4 5 6; 7 8 9];
A=[1 2 3; 4 5 6; 7 8 9]
eig(A)
v=abs(eig(A)) >= 1e-14%s.é.-kek nagyobbak-e mint 0 1:igen; 0:nem
sum(abs(v));
sum(abs(v)) == size(A,2) % 1:igen; invható; 0:nem invható

A =

   1   2   3
   4   5   6
   7   8   9

ans =

   1.6117e+01
  -1.1168e+00
  -3.7331e-16

v =

  1
  1
  0

ans = 0


In [4]:
A=[1 2 3; 4 5 6; 7 8 9];
nullasajatertek(A)

Az A matrix nem invertalhato


<br>
<b>2.feladat.</b> Írjunk programot <i>sarokdeterminans.m</i> néven, mely egy adott négyzetes mátrixra kiszámolja a sarokdeterminánsait!

In [7]:
A=[1 2 3; 4 5 6; 7 8 9];
%A=[1 1; 2 2]
for j=1:length(A)
    v(j)=det(A(1:j,1:j)); % bal felső sarokdetermináns
end
v

v =

   1.0000e+00  -3.0000e+00   6.6613e-16



In [17]:
v=sarokdeterminans(A)

v =

   1.0000e+00  -3.0000e+00   6.6613e-16



<br>
<b>3.feladat.</b> Írjunk programot <i>szdd.m</i> néven, mely eldönti, hogy a mátrix szigorúan diagonálisan domináns-e vagy sem!

In [5]:
%A=[1 2 5; 2 1 3; 5 3 4]
%A=[-1 0 2; 0 1 3; 0 1 5]
A=[4  1 1; 1 3 0; 2 -1 -7]
%A=[-4  1 1; 1 3 -3; 2 -1 -7]
sum(abs(A),2)
2*abs(diag(A))
all((2*abs(diag(A))) > sum(abs(A),2)) %1 SZDD; 0 nem SZDD

A =

   4   1   1
   1   3   0
   2  -1  -7

ans =

    6
    4
   10

ans =

    8
    6
   14

ans = 1


In [6]:
szdd(A)

Az A matrix SZDD


<br>
<b>4.feladat.</b> Írjunk programot <i>mmatrixelojel.m</i> néven, mely eldönti, hogy a mátrix az M-mátrix definícióhoz tartozó előjeleloszlás tulajdonsággal rendelkezik-e vagy sem!

<u><b>Def.</b></u> Egy $A\in\mathbb{R}^{n\times n}$ mátrixot M-mátrixnak nevezünk, ha $a_{ij}\leq 0$ minden $i\neq j$-re és létezik olyan $g>0\in\mathbb{R}^n$ vektor, hogy $Ag>0$. 

In [4]:
% Beadható M-mátrix előjel eloszlása
%A=zeros(3)
%A=[-1 1; 0 1]
A=[1 0 -2; 0 1 0; 0 -1 1]
A=A-diag(diag(A));
for j=1:length(A)
    for k=1:length(A)
        offdiag_elojel(j,k)=A(j,k)<=0;
    end
end
if sum(sum(offdiag_elojel))==length(A)^2
    disp('Az adott matrix teljesiti az M-matrixhoz tartozo elojeleloszlast')
else
    disp('Az adott matrix nem teljesiti az M-matrixhoz tartozo elojeleloszlast')
end

A =

   1   0  -2
   0   1   0
   0  -1   1

Az adott matrix teljesiti az M-matrixhoz tartozo elojeleloszlast


In [7]:
A=[1 0 -2; 0 1 0; 0 1 1]
mmatrixelojel(A)

A =

   1   0  -2
   0   1   0
   0   1   1

Az adott matrix nem teljesiti az M-matrixhoz tartozo elojeleloszlast
